<?php

try {

} catch (FirstException | SecondException $e) {
   // Обрабатываем оба исключения
}
